### ISSUE TITLE
ERROR: Some tests did not pass:

### ISSUE THREAD

**Issue by nikhoj** [vtjeng/MIPVerify.jl#110]
I tried to run the runtests.jl file and I am getting 2 error among 349 tests.

Test Summary:                      | Pass  Error  Total
MIPVerify                          |  347      2    349
  integration/                     |   34            34
  net_components/                  |  253           253
  utils/                           |   27            27
  models.jl                        |    3             3
  batch_processing_helpers/        |   15      2     17
    unit.jl                        |   15            15
    integration.jl                 |           2      2
      batch_find_untargeted_attack |           1      1
      batch_find_targeted_attack   |           1      1
  get_default_tightening_options   |    3             3
  get_max_index                    |    4             4
  get_norm                         |    8             8
ERROR: Some tests did not pass: 347 passed, 0 failed, 2 errored, 0 broken.

batch_find_untargeted_attack, batch_find_targeted_attack getting 1 error for each. Could you please guide me that what could be the issue? is this normal? my Gurobi is educational version, is it because its a restricted version?

**Comment by vtjeng** [comment]
Gurobi's education license should be fine. Would you provide a few more details on your system, including the Julia version, MIPVerify version, as well as OS?

**Comment by nikhoj** [comment]
Julia Version : v"1.7.2"
Gurobi version: v0,11.0
MIPVerify version: v0.3.1
OS: windows 64bit

Do you need anything else?

**Comment by nikhoj** [comment]
![image](https://user-images.githubusercontent.com/47932555/160146081-84d0427c-9d13-4039-b932-a80a283e236f.png)

**Comment by nikhoj** [comment]
![image](https://user-images.githubusercontent.com/47932555/160201837-e8c7348f-191a-46d3-bbf9-43ef9163c729.png)

**Comment by nikhoj** [comment]
> Julia Version : v"1.7.2" Gurobi version: v0,11.0 MIPVerify version: v0.3.1 OS: windows 64bit
> 
> Do you need anything else? Do you think windows 11 is the problem?

I ran on windows 10, still throwing the same 2 error

**Comment by vtjeng** [comment]
Our CI tests this on Windows, so I wouldn't expect it to be a problem. Are
you able to get the specific error messages from the two failing tests? The
screenshot you've taken is just to the line that summarizes the test
failure.

**Comment by nikhoj** [comment]
![image](https://user-images.githubusercontent.com/47932555/160213410-12c72daf-4cbf-4abd-b45f-1791830abbc8.png)
![image](https://user-images.githubusercontent.com/47932555/160213469-f8bc2079-77e0-48db-94dc-3e5caf55d368.png)
![image](https://user-images.githubusercontent.com/47932555/160213535-1525ae3e-f51c-4aaa-9b3b-dde2710fa1c6.png)

**Comment by vtjeng** [comment]
The error you're pointing to is coming from
https://github.com/vtjeng/MIPVerify.jl/blob/2d58aecd1819e3166acb64db6919116211b01554/src/batch_processing_helpers.jl#L142
.

How exactly are you running these tests? What version of DataFrames do you
have installed?

**Comment by nikhoj** [comment]
![image](https://user-images.githubusercontent.com/47932555/160218676-352a93d0-a864-4814-95b1-b3515334a6b7.png)


I was using Dataframes version v1.3.2, after your reply I tried downgrade the version and run with v0.21.8, but still got the issue. Do you think the image problem could be the reason for the issue?

I was running through vscode IDE, now I will try to run directly from console, I will let you know if I still get the same error.

**Comment by nikhoj** [comment]
![image](https://user-images.githubusercontent.com/47932555/160220175-ec1814c8-ec3a-485c-8bbd-283f54e66e8d.png)

After Downgrading the version it is now running, but some lines are printed after summary print out. Thank you so much @vtjeng.

**Comment by vtjeng** [comment]
No problem. I'll take a look at that and also probably see whether I can
upgrade to the newer version of DataFrames.

**Comment by vtjeng** [comment]
Quick update: The root cause turned out to be a bug in how I specified the project's dependencies (nothing to do with Windows, and not an issue on your side) that has been resolved in #112. I'll be cutting a new release for `MIPVerify.jl` and you'll see this issue fixed in 0.3.2 (that is, you won't have to manully pin `DataFrames` to an older version). 

Thanks for your patience.

**Comment by nikhoj** [comment]
Great!!! Thank you so much @vtjeng.

**Comment by vtjeng** [comment]
https://github.com/vtjeng/MIPVerify.jl/releases/tag/v0.3.2
