### ISSUE TITLE
'Valid' padding for convolutions

### ISSUE THREAD

**Issue by ssingh19** [vtjeng/MIPVerify.jl#15]
Hi,

Do you plan on adding support for 'Valid' padded convolutions, as opposed to 'Same' padding? Is there a specific section that would need to be modified (and hence, maybe I can quickly do it in my fork)?

Thanks!

**Comment by vtjeng** [comment]
We definitely do plan to add support for 'valid' padded convolutions, but I'm not sure how soon that will get done. To get it quickly done on your fork, you'd have to modify the logic here in the `conv2d` function:

https://github.com/vtjeng/MIPVerify.jl/blob/2934963/src/net_components/layers/conv2d.jl#L120-L154

It shouldn't be too challenging (I basically copied the `tensorflow` implementation to create this) but it might take a bit of work to get the convention just right.

(If you get it working, a PR is welcome!)

**Comment by ssingh19** [comment]
Thanks Vincent!

**Comment by vtjeng** [comment]
This functionality is now available as of https://github.com/vtjeng/MIPVerify.jl/pull/43
