### ISSUE TITLE
Can't find the network file?

### ISSUE THREAD

**Issue by Callmejp** [vtjeng/MIPVerify.jl#21]
Hi!
Recently l met a problem. When l installed everything needed and try your `QucikStart` tutorial. And l get the same result. But l met the error the next day (just the picture).

![捕获](https://user-images.githubusercontent.com/22981386/66393489-3ebfbd00-ea05-11e9-9d7c-5d3a595c48ab.JPG)

lt seems the program can't find the network file. So l learned your code. And l found that 
https://github.com/vtjeng/MIPVerify.jl/blob/727a3fc020c03a949b501fbe4c684dca717b5b37/src/models.jl#L5-L8

`Base.tempdir()` in my PC is '/tmp', so l got '/tmp/julia/MIPVerify/models'.
And because the following code l got the final filename. 

https://github.com/vtjeng/MIPVerify.jl/blob/727a3fc020c03a949b501fbe4c684dca717b5b37/src/models.jl#L113-L120

So the program(the following code) tries to open the `filepath`, but but but l think that l haven't found any code that writes the network file in that path before.

https://github.com/vtjeng/MIPVerify.jl/blob/727a3fc020c03a949b501fbe4c684dca717b5b37/src/models.jl#L144-L154

So is there l have missed something? After all, l am a rookie in Julia.
l'll appreciate your reply!
Thanks!

**Comment by vtjeng** [comment]
Thanks for the thorough report. Did you close the issue because you figured out a solution?

(What operating system are you on? Looks like Ubuntu 18.04?)

**Comment by Callmejp** [comment]
Sorry, when l finished the issue, l found that the program is ready to write the file(`open(... 'w') in line 150`). 
So the key is that the current user in my ubuntu hasn't permission to write the network file. l just have solved this problem.
Thanks for your reply!
But why the `Base.tempdir()` is `/tmp`? Is this fixed?

**Comment by vtjeng** [comment]
`Base.tempdir` is set by [Julia](https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.tempdir). If you'd like, you could file an issue at https://github.com/JuliaLang/julia as to why it's set as a directory that you don't have write access to.
