### ISSUE TITLE
OSX install issues w/ Gurobi

### ISSUE THREAD

**Issue by choltz95** [vtjeng/MIPVerify.jl#38]
Followed the installation instructions here: https://vtjeng.github.io/MIPVerify.jl/latest/#Installation-1 for julia v. 1.4. Get the following errors on osx Catalina:

<img width="892" alt="Screen Shot 2020-03-24 at 8 37 23 AM" src="https://user-images.githubusercontent.com/5779125/77445744-b4002e00-6daa-11ea-97b5-a4ebaf6c081b.png">

Tried for Gurobi .pkg installations versions 9.0.1, 8.0.1, 8.1.1 from https://www.gurobi.com/downloads/gurobi-software/. Is there something dumb I am missing?

**Comment by vtjeng** [comment]
That 's odd. This might be a question that is best for https://github.com/JuliaOpt/Gurobi.jl; unfortunately I've never tried installation on `osx` (I haven't gotten our CI tests working on `osx`, but it might still work). Would you try asking the folks at `Gurobi.jl`?

**Comment by vtjeng** [comment]
Did you manage to fix the issue? If so, I'd appreciate if you could share the steps.

**Comment by vtjeng** [comment]
Closing out old issue.
