### ISSUE TITLE
Avoid using Memento.getparent

### ISSUE THREAD

**Issue by omus** [vtjeng/MIPVerify.jl#4]
The `Memento.getparent` function was an internal function in Memento and was removed as of v0.8.0. This change will cause the following code to break:

https://github.com/vtjeng/MIPVerify.jl/blob/40290837199b355e0c8747a2bf2053e6b49c9abf/src/logging.jl#L22

See the conversation in https://github.com/JuliaLang/METADATA.jl/pull/15389 about possible solutions.

**Comment by vtjeng** [comment]
Fixed in https://github.com/vtjeng/MIPVerify.jl/commit/1ed0ea1d33360f932ebdc5d5ee05c87fcc8b003b.
