### ISSUE TITLE
Accessing MILP problem instance

### ISSUE THREAD

**Issue by marti-mcfly** [vtjeng/MIPVerify.jl#42]
Is it possible to access the MILP problem instance without actually solving it, i.e. passing it to the solver? I believe it is formulated somewhere inside find_adversarial_example() but I am not sure. Any pointers would be appreciated.

**Comment by vtjeng** [comment]
> Marty, the way I see it, if you're going to build a MILP problem instance in Julia, why not do it with some style?

--------------------------

Jokes aside: yes, it's formulated in `find_adversarial_example`. The model with the constraints on the inputs and the intermediate network activations is constructed here: 

https://github.com/vtjeng/MIPVerify.jl/blob/727a3fc020c03a949b501fbe4c684dca717b5b37/src/MIPVerify.jl#L121 

Depending on the adversarial example objective, you need to add a few more constraints, and set an appropriate objective. In the documentation below, "target indexes" correspond to those indexes that we are (adversarially) trying to set the network's prediction to.

# Closest
If you're looking for the closest adversarial example, you have to add a constraint that the target indexes have an activation greater than those of the non-target indexes, by the `tolerance` margin:

https://github.com/vtjeng/MIPVerify.jl/blob/727a3fc020c03a949b501fbe4c684dca717b5b37/src/MIPVerify.jl#L126

Your optimization objective is to minimize the perturbation:

https://github.com/vtjeng/MIPVerify.jl/blob/727a3fc020c03a949b501fbe4c684dca717b5b37/src/MIPVerify.jl#L131

# Worst
If you're looking for the "worst" adversarial example, we add two additional variables corresponding to the maximum value of the target indexes and the non-target indexes: 

https://github.com/vtjeng/MIPVerify.jl/blob/727a3fc020c03a949b501fbe4c684dca717b5b37/src/MIPVerify.jl#L133-L134

Your optimization objective is to maximize the difference in activations:

https://github.com/vtjeng/MIPVerify.jl/blob/727a3fc020c03a949b501fbe4c684dca717b5b37/src/MIPVerify.jl#L135
