### ISSUE TITLE
How does maxpooling layer process Gurobi variable?

### ISSUE THREAD

**Issue by UserAlreadyTaken** [vtjeng/MIPVerify.jl#46]
maxpooling will choose the max element from the kernel, but you don't know the specific value of the node, it just gurobi variable or expression. I want to know how does it choose the max element.

**Comment by vtjeng** [comment]
To implement max-pooling, it suffices to be able to implement the `max` _constraint_, that is, to be able to set `y` such that

```
y = max(x_1, x_2, . . . , x_m)
```

Here is the reference from Section 4.1 of the paper. Note the introduction of the (binary) variable `a_i`, which allows the value of the output variables to be constrained as a function of the input variable.

![image](https://user-images.githubusercontent.com/5932817/81306842-cff72080-9034-11ea-9ff5-6559ee88a945.png)

For reference, the implementation in code is here: https://github.com/vtjeng/MIPVerify.jl/blob/727a3fc020c03a949b501fbe4c684dca717b5b37/src/net_components/core_ops.jl#L304-L340

**Comment by vtjeng** [comment]
Closing as addressed since we haven't had any replies in a while.
