### ISSUE TITLE
Wrong download URL on Windows

### ISSUE THREAD

**Issue by zomborid** [vtjeng/MIPVerify.jl#90]
On Windows the `joinpath` command uses `\` as a separator which breaks download of resources.
Since backslash is not used in URLs, simply replacing them fixes the problem.
By inserting the following line after `src/utils/prep_data_file.jl:12`, all MIPVerify tests pass. (In Julia 1.6-rc3.)
`url = replace(url, "\\" => "/")`

Example implementation:
```
url_raw = joinpath(data_repo_path, relative_file_path)
url = replace(url_raw, "\\" => "/")
download(url, absolute_file_path)
```

Best regards,
Dániel

**Comment by vtjeng** [comment]
Thanks, @zomborid. This should now be available in the https://github.com/vtjeng/MIPVerify.jl/releases/tag/v0.3.1 release, which you can get by [upgrading the package](https://pkgdocs.julialang.org/v1/managing-packages/#updating).
